list(APPEND SDKCONFIG_DEFAULTS
    boards/ESP32_GENERIC/sdkconfig.romfs
)

list(APPEND MICROPY_DEF_BOARD
	MICROPY_HW_BOARD_NAME="Generic ESP32 module with ROMFS"
	# Enable ROMFS
	MICROPY_VFS_ROM=1
	MICROPY_VFS_ROM_IOCTL=1
)
